# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre proyecto')),
                ('tipo_proyecto', models.CharField(choices=[('I', 'Interno'), ('E', 'Externo')], max_length=1, verbose_name='Proyecto: INTERNO o EXTERNO')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripcion del proyecto')),
                ('estado', models.CharField(choices=[('SI', 'asignado'), ('NO', 'no asignado')], max_length=10, verbose_name='Proyecto: Asignado o NO Asignado')),
                ('matricula', models.CharField(max_length=10, verbose_name='Matricula Asignada')),
                ('archivo', models.FileField(upload_to='blog/archivos', verbose_name='subir archivo')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='empresas.Empresa')),
            ],
        ),
    ]
