# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('titularempresa', models.CharField(max_length=150, verbose_name='Titular de la Empresa')),
                ('giro', models.CharField(blank=True, max_length=100, verbose_name='Giro de la Empresa')),
                ('titularproyecto', models.CharField(max_length=150, verbose_name='Titular del Proyecto')),
                ('direccion', models.CharField(max_length=255, verbose_name='Calle y Numero')),
                ('colonia', models.CharField(max_length=255, verbose_name='Colonia')),
                ('codigo_postal', models.CharField(max_length=50, verbose_name='Codigo Postal')),
                ('rfc', models.CharField(max_length=100, verbose_name='RFC')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('social', models.CharField(blank=True, max_length=255, verbose_name='Redes Sociales')),
            ],
        ),
    ]
